### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by dpizetta** [dpizetta/wavy#2]
Here is the message:

Traceback (most recent call last):
  File "/home/pizetta/workspace/wavy/wavy/gui_wavy.py", line 119, in updateplot
    self.data[self.ptr] = self.getdata()
  File "/home/pizetta/workspace/wavy/wavy/gui_wavy.py", line 116, in getdata
    return global_buffer.data[global_buffer.counter - 1]
IndexError: index 381 is out of bounds for axis 0 with size 50

**Comment by dpizetta** [comment]
Actually the first message is:

index 50 is out of bounds for axis 0 with size 50. May needs change in the if statement.
